---
title: "Assignment 5"
author: "Santhosh reddy Mallikireddy"
date: "07/10/2019"
output: html_document
---
Assignment 5:- R code for Q1 and Q2

5(Q1) R program:

The longest path is the critical path which is (1-2-5-7-9) = 17. 
```{r}
library(lpSolveAPI)

## create IP object
Network_object <- make.lp(nrow = 9, ncol = 12) # nrow is the number of nodes, ncol is the numnber of arcs
lp.control(Network_object, sense="max")

# create names for nodes and arcs
arc <- c("x12", "x13", "x24", "x25", "x35", "x46", "x47", "x57", "x58", "x69", "x79", "x89")
node <- c("node1", "node2", "node3", "node4", "node5", "node6", "node7", "node8", "node9")

# rename the IP object
rownames(Network_object) <- node
colnames(Network_object) <- arc

## objective function
time <- c(5, 3, 4, 2, 3, 1, 4, 6, 2, 5, 4, 7)
set.objfn(Network_object, 1*time)

# node 1 "starting node"
set.row(Network_object, 1, c(1,1), indices = c(1,2))

# node 2:8 "intermediate node"
set.row(Network_object, 2, c(1,-1,-1), indices = c(1,3,4))
set.row(Network_object, 3, c(1,-1), indices = c(2,5))
set.row(Network_object, 4, c(1,-1,-1), indices = c(3,6,7))
set.row(Network_object, 5, c(1,1,-1,-1), indices = c(4,5,8,9))
set.row(Network_object, 6, c(1, -1),indices = c(6,10))
set.row(Network_object, 7, c(1,1,-1), indices = c(7,8,11))
set.row(Network_object, 8, c(1,-1), indices = c(9,12))

# node 9 "finish node"
set.row(Network_object, 9, c(1,1,1), indices = c(10,11,12))

## set constraints type
set.constr.type(Network_object, rep("="), 9)

## set constraint RHS
rhs <- c(1, rep(0, 7), 1)
set.rhs(Network_object, rhs)

## set all variables type to be binary
set.type(Network_object, 1:12, "binary") 
write.lp(Network_object, "netlp.lp", "lp")

## solve
solve(Network_object)
get.objective(Network_object)
get.variables(Network_object)

# put optimal values beside of variable names for better understanding of th results
cbind(arc, get.variables(Network_object))
```

5(Q2)a:
with interger restriction

```{r}
library(lpSolveAPI)
lprec<-make.lp(0,8)
lp.control(lprec,sense="max")
set.objfn(lprec,c(4,6.5,5.9,5.4,5.15,10,8.4,6.25))
set.type(lprec,c(1:8),type = "integer") #by commenting this we can remove interger restriction.
add.constraint(lprec,c(40,50,80,60,45,60,30,25),"<=",2500000,indices = c(1:8))
add.constraint(lprec,1000,">=",0,indices = 1)
add.constraint(lprec,1000,">=",0,indices = 2)
add.constraint(lprec,1000,">=",0,indices = 3)
add.constraint(lprec,1000,">=",0,indices = 4)
add.constraint(lprec,1000,">=",0,indices = 5)
add.constraint(lprec,1000,">=",0,indices = 6)
add.constraint(lprec,1000,">=",0,indices = 7)
add.constraint(lprec,1000,">=",0,indices = 8)
add.constraint(lprec,40,">=",100000,indices = 1)
add.constraint(lprec,50,">=",100000,indices = 2)
add.constraint(lprec,80,">=",100000,indices = 3)
add.constraint(lprec,60,">=",100000,indices = 4)
add.constraint(lprec,45,">=",100000,indices = 5)
add.constraint(lprec,60,">=",100000,indices = 6)
add.constraint(lprec,30,">=",100000,indices = 7)
add.constraint(lprec,25,">=",100000,indices = 8)
add.constraint(lprec,c(40,50,80),"<=",500000,indices = c(1,2,3))
add.constraint(lprec,c(60,45,60),"<=",1000000,indices = c(4,5,6))
add.constraint(lprec,c(30,25),"<=",1000000,indices = c(7,8))
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)
```

5(Q2) b:
without integer restriction
```{r}
library(lpSolveAPI)
lprec<-make.lp(0,8)
lp.control(lprec,sense="max")
set.objfn(lprec,c(4,6.5,5.9,5.4,5.15,10,8.4,6.25))
add.constraint(lprec,c(40,50,80,60,45,60,30,25),"<=",2500000,indices = c(1:8))
add.constraint(lprec,1000,">=",0,indices = 1)
add.constraint(lprec,1000,">=",0,indices = 2)
add.constraint(lprec,1000,">=",0,indices = 3)
add.constraint(lprec,1000,">=",0,indices = 4)
add.constraint(lprec,1000,">=",0,indices = 5)
add.constraint(lprec,1000,">=",0,indices = 6)
add.constraint(lprec,1000,">=",0,indices = 7)
add.constraint(lprec,1000,">=",0,indices = 8)
add.constraint(lprec,40,">=",100000,indices = 1)
add.constraint(lprec,50,">=",100000,indices = 2)
add.constraint(lprec,80,">=",100000,indices = 3)
add.constraint(lprec,60,">=",100000,indices = 4)
add.constraint(lprec,45,">=",100000,indices = 5)
add.constraint(lprec,60,">=",100000,indices = 6)
add.constraint(lprec,30,">=",100000,indices = 7)
add.constraint(lprec,25,">=",100000,indices = 8)
add.constraint(lprec,c(40,50,80),"<=",1000000,indices = c(1,2,3))
add.constraint(lprec,c(60,45,60),"<=",1000000,indices = c(4,5,6))
add.constraint(lprec,c(30,25),"<=",1000000,indices = c(7,8))
solve(lprec)
get.objective(lprec)
get.variables(lprec)
get.constraints(lprec)
```


